### PR TITLE
WiFiManager second try

### PR DESCRIPTION
**Pull request by puuu**
Here is my alternative implementation of the WiFiManager. I removed the old wifi config parameter, since they are stored in flash and survive an update. The ota password is now the admin password and should be later managed by the Settings module as common administration password (ota, wifimanage, web interface). Now using HeartbeatFlashing for proper status signalling (slow flashing = connecting to wifi, fast flashing = ap mode). 

I am not a big fan of the implementation of the WiFiManager. For example, they do not use streaming but a [long String variable](https://github.com/tzapu/WiFiManager/blob/master/WiFiManager.cpp#L405) to generate and deliver the html data. This buffers everything twice and lead to heap fragmentation. At the end we can run out of memory, if there are many wifi networks.

Also there is no easy way to provide a static ip configuration.

### CODE REVIEW

**Comment by janLo** [comment]
I wanted to provide a static configuration for people who compiled their own version. Also I wanted to keep the passwords separated as the portal password should definitely not set to a general default as it secures an operation when the instance is connected to a network while the wifi manager password is only relevant when there is not network connection and can be happily set to a default that we can write in the documentation.

Regarding the memory usage of the portal, it would even be no problem to just reboot the device after configuration.

For the orange, I'm not sure yet if the mqtt version should not be replaced by a web version where the user can upload the binary via a browser.

**Comment by puuu** [comment]
People how compiled their own version, can also flash once a small program that configure the wifi and after this, they can flash the MQTT433gateway.

I think having multiple passwords on one device is to complicated. It will not enhance the security for normal user, since most of them will not change all passwords. Having only one general will be better. Then we can force the user to change this password (e.g., do not connect to mqtt and do not start ESPiLight). Having a default password, that is written in the documentation has the same worse security then no password. My idea is to use one admin password which by default is not set (or can be find in the docs). On the first start, the WiFiManager use this password, after connection to wifi, the user must change the password with the web interface, before the MQTT433gateway will provide full operation.

If we have a web interface, ota over mqtt can be replaced with ota over web interface.

**Comment by puuu** [comment]
Also I want to get rid of the `config.h` file. With regard to your Settings module, the aim should be a `.json` config file that will be on-the-fly converted to a `.h` file.

**Comment by puuu** [comment]
Close because addressed in #21.

**Pull request closed without merging**
