### PR TITLE
Make Serial debug optional

### PR DESCRIPTION
**Pull request by janLo**
This wrapps all `Serial.print()` into a macro to be able to switch the logging off at compile-time. Without it, there is more power for protocoll processing.

This is based on PR #15.

### CODE REVIEW

**Comment by puuu** [comment]
Debugging or Logging? Many of this messages are helpful for the user and support. 

We should not make the Gateway silent.

**Comment by janLo** [comment]
I think the serial pronting is purely debugging, as teh device is not intended to have a serial adapter attached. However, I think its a waste of essources to pump stuff to the UART no matter if its connected to anything. My devices are a ESP-12E which are only connected to a serial adapter to get falshed (or debugged).

For logging or debugging y the enduser I would suggest to use something like [Syslog](https://github.com/arcao/Syslog) or having a log-view in the Frontend. The [esp8266_milight_hub](https://github.com/sidoh/esp8266_milight_hub) is a good example how to present log messages in a frontend.

**Comment by puuu** [comment]
I think, serial logging, did not waste that much resources on a ESP, at least until now it did not.

I just say, we should not make the gateway silent. Logging is a important behavior. Mostly you are not required to see the logs, but if you run into trouble you are happy about logs. Using a simple lib is fine and a alternative log-view frontend would be nice.

syslog might be a little bit overkill.

**Comment by janLo** [comment]
Actually syslog is pretty simple. You just push some packets over UDP. To receive them you can just have a simple script. I built this for another project: https://github.com/Retardigrades/tent-update-controller/blob/master/syslog_receiver.py

**Comment by janLo** [comment]
The sender side could then look like https://github.com/Retardigrades/tent-gyro-esp/blob/master/src/log.h

**Comment by puuu** [comment]
Merged in dba9a95a62b3f6dc76de5bbf8d54d4ac0f1f69d0 .

**Pull request closed without merging**
